### ISSUE TITLE
 Call to undefined method Feature::getRelativeScreenshotPath

### ISSUE THREAD

**Issue by Atadilo** [dutchiexl/BehatHtmlFormatterPlugin#103]
On branch master, I get this stack trace : 
```
PHP Fatal error:  Uncaught Error: Call to undefined method emuse\BehatHTMLFormatter\Classes\Feature::getRelativeScreenshotPath() in .../vendor/emuse/behat-html-formatter/src/Renderer/Behat2Renderer.php:437
Stack trace:
#0 .../vendor/emuse/behat-html-formatter/src/Renderer/BaseRenderer.php(255): emuse\BehatHTMLFormatter\Renderer\Behat2Renderer->renderAfterStep(Object(emuse\BehatHTMLFormatter\Formatter\BehatHTMLFormatter))
#1 .../vendor/emuse/behat-html-formatter/src/Formatter/BehatHTMLFormatter.php(636): emuse\BehatHTMLFormatter\Renderer\BaseRenderer->renderAfterStep(Object(emuse\BehatHTMLFormatter\Formatter\BehatHTMLFormatter))
#2 [internal function]: emuse\BehatHTMLFormatter\Formatter\BehatHTMLFormatter->onAfterStepTested(Object(Behat\Behat\EventDispatcher\Event\AfterStepTested), 'tester.step_tes...', Object(Behat\Testwork\EventDispatcher\TestworkEventDispatcher))
#3 in .../vendor/emuse/behat-html-formatter/src/Renderer/Behat2Renderer.php on line 437
```
Is the function `getRelativeScreenshotPath()` missing in `emuse\BehatHTMLFormatter\Classes\Feature`? 
Or is lines in `Behat2Renderer.php` must be `$scenario`instead of `$feature` ?
Or other solutions ?

Thanks :)

**Comment by donkidd** [comment]
@Atadilo I had the same issue so I fixed it in my fork, per your suggestion, hopefully the PR with get approved and the fix will be applied.
